### ISSUE TITLE
C style comments

### ISSUE THREAD

**Issue by KatJon** [KNSI-PWr/lp2jvm#3]
I'm not sure, but we discusssed, that there will be bash-style comments (#).

**Comment by repaj** [comment]
I used to add it, but I reckon that previous grammar was invalid at all, e.g. lexer rules weren't ordered, so I rewrite all grammar as new one from scratch. I can modify this to bash-style comments, if nessesary.

**Comment by KatJon** [comment]
Not so necessary, but I wasn't sure if that was intended, for me it's ok.

**Comment by repaj** [comment]
By the way, I based this grammar on built-in snippets in ANTLR4 plugin for IntelliJ. Because I don't want to spend my precious time on writing this from very basic things, I used it. 😛
